// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: vultisig/keysign/v1/1inch_swap_payload.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneInchTransaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From     string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data     string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Value    string `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	GasPrice string `protobuf:"bytes,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Gas      int64  `protobuf:"varint,6,opt,name=gas,proto3" json:"gas,omitempty"`
	SwapFee  string `protobuf:"bytes,7,opt,name=swap_fee,json=swapFee,proto3" json:"swap_fee,omitempty"`
}

func (x *OneInchTransaction) Reset() {
	*x = OneInchTransaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneInchTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneInchTransaction) ProtoMessage() {}

func (x *OneInchTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneInchTransaction.ProtoReflect.Descriptor instead.
func (*OneInchTransaction) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescGZIP(), []int{0}
}

func (x *OneInchTransaction) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *OneInchTransaction) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *OneInchTransaction) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *OneInchTransaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *OneInchTransaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *OneInchTransaction) GetGas() int64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *OneInchTransaction) GetSwapFee() string {
	if x != nil {
		return x.SwapFee
	}
	return ""
}

type OneInchQuote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstAmount string              `protobuf:"bytes,1,opt,name=dst_amount,json=dstAmount,proto3" json:"dst_amount,omitempty"`
	Tx        *OneInchTransaction `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *OneInchQuote) Reset() {
	*x = OneInchQuote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneInchQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneInchQuote) ProtoMessage() {}

func (x *OneInchQuote) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneInchQuote.ProtoReflect.Descriptor instead.
func (*OneInchQuote) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescGZIP(), []int{1}
}

func (x *OneInchQuote) GetDstAmount() string {
	if x != nil {
		return x.DstAmount
	}
	return ""
}

func (x *OneInchQuote) GetTx() *OneInchTransaction {
	if x != nil {
		return x.Tx
	}
	return nil
}

type OneInchSwapPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromCoin        *Coin         `protobuf:"bytes,1,opt,name=from_coin,json=fromCoin,proto3" json:"from_coin,omitempty"`
	ToCoin          *Coin         `protobuf:"bytes,2,opt,name=to_coin,json=toCoin,proto3" json:"to_coin,omitempty"`
	FromAmount      string        `protobuf:"bytes,3,opt,name=from_amount,json=fromAmount,proto3" json:"from_amount,omitempty"`
	ToAmountDecimal string        `protobuf:"bytes,4,opt,name=to_amount_decimal,json=toAmountDecimal,proto3" json:"to_amount_decimal,omitempty"`
	Quote           *OneInchQuote `protobuf:"bytes,5,opt,name=quote,proto3" json:"quote,omitempty"`
}

func (x *OneInchSwapPayload) Reset() {
	*x = OneInchSwapPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneInchSwapPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneInchSwapPayload) ProtoMessage() {}

func (x *OneInchSwapPayload) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneInchSwapPayload.ProtoReflect.Descriptor instead.
func (*OneInchSwapPayload) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescGZIP(), []int{2}
}

func (x *OneInchSwapPayload) GetFromCoin() *Coin {
	if x != nil {
		return x.FromCoin
	}
	return nil
}

func (x *OneInchSwapPayload) GetToCoin() *Coin {
	if x != nil {
		return x.ToCoin
	}
	return nil
}

func (x *OneInchSwapPayload) GetFromAmount() string {
	if x != nil {
		return x.FromAmount
	}
	return ""
}

func (x *OneInchSwapPayload) GetToAmountDecimal() string {
	if x != nil {
		return x.ToAmountDecimal
	}
	return ""
}

func (x *OneInchSwapPayload) GetQuote() *OneInchQuote {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_vultisig_keysign_v1_1inch_swap_payload_proto protoreflect.FileDescriptor

var file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69,
	0x67, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x31, 0x69, 0x6e, 0x63, 0x68, 0x5f, 0x73, 0x77, 0x61, 0x70,
	0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13,
	0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65,
	0x79, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x12, 0x4f, 0x6e, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x67, 0x61, 0x73, 0x5f,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x73,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x67, 0x61, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x77, 0x61, 0x70, 0x5f,
	0x66, 0x65, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x77, 0x61, 0x70, 0x46,
	0x65, 0x65, 0x22, 0x66, 0x0a, 0x0c, 0x4f, 0x6e, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x73, 0x74, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x73, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x37, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x74, 0x78, 0x22, 0x86, 0x02, 0x0a, 0x12, 0x4f,
	0x6e, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x53, 0x77, 0x61, 0x70, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x36, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e,
	0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52,
	0x08, 0x66, 0x72, 0x6f, 0x6d, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x32, 0x0a, 0x07, 0x74, 0x6f, 0x5f,
	0x63, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x75, 0x6c,
	0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a,
	0x0a, 0x11, 0x74, 0x6f, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x63, 0x69,
	0x6d, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x74, 0x6f, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x05, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x75, 0x6c, 0x74,
	0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4f, 0x6e, 0x65, 0x49, 0x6e, 0x63, 0x68, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x05, 0x71, 0x75,
	0x6f, 0x74, 0x65, 0x42, 0x54, 0x0a, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e,
	0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x75,
	0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0xba, 0x02, 0x02, 0x56, 0x53, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescOnce sync.Once
	file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescData = file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDesc
)

func file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescGZIP() []byte {
	file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescOnce.Do(func() {
		file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescData)
	})
	return file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDescData
}

var file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vultisig_keysign_v1_1inch_swap_payload_proto_goTypes = []any{
	(*OneInchTransaction)(nil), // 0: vultisig.keysign.v1.OneInchTransaction
	(*OneInchQuote)(nil),       // 1: vultisig.keysign.v1.OneInchQuote
	(*OneInchSwapPayload)(nil), // 2: vultisig.keysign.v1.OneInchSwapPayload
	(*Coin)(nil),               // 3: vultisig.keysign.v1.Coin
}
var file_vultisig_keysign_v1_1inch_swap_payload_proto_depIdxs = []int32{
	0, // 0: vultisig.keysign.v1.OneInchQuote.tx:type_name -> vultisig.keysign.v1.OneInchTransaction
	3, // 1: vultisig.keysign.v1.OneInchSwapPayload.from_coin:type_name -> vultisig.keysign.v1.Coin
	3, // 2: vultisig.keysign.v1.OneInchSwapPayload.to_coin:type_name -> vultisig.keysign.v1.Coin
	1, // 3: vultisig.keysign.v1.OneInchSwapPayload.quote:type_name -> vultisig.keysign.v1.OneInchQuote
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_vultisig_keysign_v1_1inch_swap_payload_proto_init() }
func file_vultisig_keysign_v1_1inch_swap_payload_proto_init() {
	if File_vultisig_keysign_v1_1inch_swap_payload_proto != nil {
		return
	}
	file_vultisig_keysign_v1_coin_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OneInchTransaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OneInchQuote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*OneInchSwapPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vultisig_keysign_v1_1inch_swap_payload_proto_goTypes,
		DependencyIndexes: file_vultisig_keysign_v1_1inch_swap_payload_proto_depIdxs,
		MessageInfos:      file_vultisig_keysign_v1_1inch_swap_payload_proto_msgTypes,
	}.Build()
	File_vultisig_keysign_v1_1inch_swap_payload_proto = out.File
	file_vultisig_keysign_v1_1inch_swap_payload_proto_rawDesc = nil
	file_vultisig_keysign_v1_1inch_swap_payload_proto_goTypes = nil
	file_vultisig_keysign_v1_1inch_swap_payload_proto_depIdxs = nil
}
