// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: vultisig/keysign/v1/dapp_metadata.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DAppMetadata identifies the dApp that asked for a signature. It is carried
// by both KeysignPayload (transactions) and CustomMessagePayload (message
// signing) so every co-signing device can show who is asking.
//
// All fields are untrusted: they are declared by the initiating device and
// covered by no signature. Consumers must treat them as display-only and must
// not use them for authorization or routing.
type DAppMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Human-readable name of the dApp. Chosen by the dApp's page, so it is not
	// an identifier and not guaranteed unique. May be empty.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Origin of the requesting dApp: scheme and host, plus port when present
	// (e.g. "https://app.example.com"). No path, query or fragment.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// URL of the dApp's icon. Chosen by the dApp's page; consumers should
	// validate the scheme before fetching it. May be empty.
	IconUrl string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
}

func (x *DAppMetadata) Reset() {
	*x = DAppMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_dapp_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DAppMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DAppMetadata) ProtoMessage() {}

func (x *DAppMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_dapp_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DAppMetadata.ProtoReflect.Descriptor instead.
func (*DAppMetadata) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_dapp_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DAppMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DAppMetadata) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DAppMetadata) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

var File_vultisig_keysign_v1_dapp_metadata_proto protoreflect.FileDescriptor

var file_vultisig_keysign_v1_dapp_metadata_proto_rawDesc = []byte{
	0x0a, 0x27, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69,
	0x67, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x70, 0x70, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69,
	0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x4f,
	0x0a, 0x0c, 0x44, 0x41, 0x70, 0x70, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x42,
	0x54, 0x0a, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73,
	0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73,
	0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0xba, 0x02, 0x02, 0x56, 0x53, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vultisig_keysign_v1_dapp_metadata_proto_rawDescOnce sync.Once
	file_vultisig_keysign_v1_dapp_metadata_proto_rawDescData = file_vultisig_keysign_v1_dapp_metadata_proto_rawDesc
)

func file_vultisig_keysign_v1_dapp_metadata_proto_rawDescGZIP() []byte {
	file_vultisig_keysign_v1_dapp_metadata_proto_rawDescOnce.Do(func() {
		file_vultisig_keysign_v1_dapp_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_vultisig_keysign_v1_dapp_metadata_proto_rawDescData)
	})
	return file_vultisig_keysign_v1_dapp_metadata_proto_rawDescData
}

var file_vultisig_keysign_v1_dapp_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vultisig_keysign_v1_dapp_metadata_proto_goTypes = []any{
	(*DAppMetadata)(nil), // 0: vultisig.keysign.v1.DAppMetadata
}
var file_vultisig_keysign_v1_dapp_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vultisig_keysign_v1_dapp_metadata_proto_init() }
func file_vultisig_keysign_v1_dapp_metadata_proto_init() {
	if File_vultisig_keysign_v1_dapp_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vultisig_keysign_v1_dapp_metadata_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DAppMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vultisig_keysign_v1_dapp_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vultisig_keysign_v1_dapp_metadata_proto_goTypes,
		DependencyIndexes: file_vultisig_keysign_v1_dapp_metadata_proto_depIdxs,
		MessageInfos:      file_vultisig_keysign_v1_dapp_metadata_proto_msgTypes,
	}.Build()
	File_vultisig_keysign_v1_dapp_metadata_proto = out.File
	file_vultisig_keysign_v1_dapp_metadata_proto_rawDesc = nil
	file_vultisig_keysign_v1_dapp_metadata_proto_goTypes = nil
	file_vultisig_keysign_v1_dapp_metadata_proto_depIdxs = nil
}
