// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: vultisig/keysign/v1/utxo_info.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardanoTokenAsset describes a Cardano native asset present on a UTXO.
// Native assets are identified by (policy_id, asset_name) with integer
// quantities. See https://docs.cardano.org/developer-resources/native-tokens.
type CardanoTokenAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hex-encoded policy id (28 bytes / 56 hex chars).
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Hex-encoded asset name (0..32 bytes / 0..64 hex chars). Empty for the
	// unnamed asset under a policy.
	AssetNameHex string `protobuf:"bytes,2,opt,name=asset_name_hex,json=assetNameHex,proto3" json:"asset_name_hex,omitempty"`
	// Token quantity in the asset's base units, as a decimal string to fit
	// values outside int64 range.
	Amount string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CardanoTokenAsset) Reset() {
	*x = CardanoTokenAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_utxo_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CardanoTokenAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardanoTokenAsset) ProtoMessage() {}

func (x *CardanoTokenAsset) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_utxo_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardanoTokenAsset.ProtoReflect.Descriptor instead.
func (*CardanoTokenAsset) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_utxo_info_proto_rawDescGZIP(), []int{0}
}

func (x *CardanoTokenAsset) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *CardanoTokenAsset) GetAssetNameHex() string {
	if x != nil {
		return x.AssetNameHex
	}
	return ""
}

func (x *CardanoTokenAsset) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type UtxoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// For UTXO chains other than Cardano, this is the UTXO amount in the
	// chain's smallest unit (e.g. satoshis). For Cardano, this is the
	// lovelace amount on the UTXO; per-UTXO native assets live in
	// cardano_tokens.
	Amount int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Index  uint32 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	// Cardano-only: native assets carried by this UTXO. Empty for non-Cardano
	// chains and for ADA-only UTXOs.
	CardanoTokens []*CardanoTokenAsset `protobuf:"bytes,4,rep,name=cardano_tokens,json=cardanoTokens,proto3" json:"cardano_tokens,omitempty"`
}

func (x *UtxoInfo) Reset() {
	*x = UtxoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_utxo_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UtxoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtxoInfo) ProtoMessage() {}

func (x *UtxoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_utxo_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtxoInfo.ProtoReflect.Descriptor instead.
func (*UtxoInfo) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_utxo_info_proto_rawDescGZIP(), []int{1}
}

func (x *UtxoInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *UtxoInfo) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UtxoInfo) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *UtxoInfo) GetCardanoTokens() []*CardanoTokenAsset {
	if x != nil {
		return x.CardanoTokens
	}
	return nil
}

var File_vultisig_keysign_v1_utxo_info_proto protoreflect.FileDescriptor

var file_vultisig_keysign_v1_utxo_info_proto_rawDesc = []byte{
	0x0a, 0x23, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69,
	0x67, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x74, 0x78, 0x6f, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e,
	0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x6e, 0x0a, 0x11, 0x43, 0x61,
	0x72, 0x64, 0x61, 0x6e, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x48,
	0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x08, 0x55,
	0x74, 0x78, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x4d, 0x0a, 0x0e, 0x63, 0x61, 0x72,
	0x64, 0x61, 0x6e, 0x6f, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79,
	0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x61, 0x6e, 0x6f, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x0d, 0x63, 0x61, 0x72, 0x64, 0x61,
	0x6e, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x42, 0x54, 0x0a, 0x13, 0x76, 0x75, 0x6c, 0x74,
	0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74,
	0x69, 0x73, 0x69, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x2f,
	0x67, 0x6f, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73,
	0x69, 0x67, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xba, 0x02, 0x02, 0x56, 0x53, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vultisig_keysign_v1_utxo_info_proto_rawDescOnce sync.Once
	file_vultisig_keysign_v1_utxo_info_proto_rawDescData = file_vultisig_keysign_v1_utxo_info_proto_rawDesc
)

func file_vultisig_keysign_v1_utxo_info_proto_rawDescGZIP() []byte {
	file_vultisig_keysign_v1_utxo_info_proto_rawDescOnce.Do(func() {
		file_vultisig_keysign_v1_utxo_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_vultisig_keysign_v1_utxo_info_proto_rawDescData)
	})
	return file_vultisig_keysign_v1_utxo_info_proto_rawDescData
}

var file_vultisig_keysign_v1_utxo_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vultisig_keysign_v1_utxo_info_proto_goTypes = []any{
	(*CardanoTokenAsset)(nil), // 0: vultisig.keysign.v1.CardanoTokenAsset
	(*UtxoInfo)(nil),          // 1: vultisig.keysign.v1.UtxoInfo
}
var file_vultisig_keysign_v1_utxo_info_proto_depIdxs = []int32{
	0, // 0: vultisig.keysign.v1.UtxoInfo.cardano_tokens:type_name -> vultisig.keysign.v1.CardanoTokenAsset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vultisig_keysign_v1_utxo_info_proto_init() }
func file_vultisig_keysign_v1_utxo_info_proto_init() {
	if File_vultisig_keysign_v1_utxo_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vultisig_keysign_v1_utxo_info_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CardanoTokenAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_utxo_info_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UtxoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vultisig_keysign_v1_utxo_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vultisig_keysign_v1_utxo_info_proto_goTypes,
		DependencyIndexes: file_vultisig_keysign_v1_utxo_info_proto_depIdxs,
		MessageInfos:      file_vultisig_keysign_v1_utxo_info_proto_msgTypes,
	}.Build()
	File_vultisig_keysign_v1_utxo_info_proto = out.File
	file_vultisig_keysign_v1_utxo_info_proto_rawDesc = nil
	file_vultisig_keysign_v1_utxo_info_proto_goTypes = nil
	file_vultisig_keysign_v1_utxo_info_proto_depIdxs = nil
}
