// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: vultisig/keysign/v1/wasm_execute_contract_payload.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CosmosCoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom  string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *CosmosCoin) Reset() {
	*x = CosmosCoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosCoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosCoin) ProtoMessage() {}

func (x *CosmosCoin) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosCoin.ProtoReflect.Descriptor instead.
func (*CosmosCoin) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{0}
}

func (x *CosmosCoin) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *CosmosCoin) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type CosmosFee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount   []*CosmosCoin `protobuf:"bytes,1,rep,name=amount,proto3" json:"amount,omitempty"`
	Gas      string        `protobuf:"bytes,2,opt,name=gas,proto3" json:"gas,omitempty"`
	Payer    *string       `protobuf:"bytes,3,opt,name=payer,proto3,oneof" json:"payer,omitempty"`
	Granter  *string       `protobuf:"bytes,4,opt,name=granter,proto3,oneof" json:"granter,omitempty"`
	FeePayer *string       `protobuf:"bytes,5,opt,name=fee_payer,json=feePayer,proto3,oneof" json:"fee_payer,omitempty"`
}

func (x *CosmosFee) Reset() {
	*x = CosmosFee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosFee) ProtoMessage() {}

func (x *CosmosFee) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosFee.ProtoReflect.Descriptor instead.
func (*CosmosFee) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{1}
}

func (x *CosmosFee) GetAmount() []*CosmosCoin {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CosmosFee) GetGas() string {
	if x != nil {
		return x.Gas
	}
	return ""
}

func (x *CosmosFee) GetPayer() string {
	if x != nil && x.Payer != nil {
		return *x.Payer
	}
	return ""
}

func (x *CosmosFee) GetGranter() string {
	if x != nil && x.Granter != nil {
		return *x.Granter
	}
	return ""
}

func (x *CosmosFee) GetFeePayer() string {
	if x != nil && x.FeePayer != nil {
		return *x.FeePayer
	}
	return ""
}

type CosmosMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *CosmosMsg) Reset() {
	*x = CosmosMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CosmosMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosmosMsg) ProtoMessage() {}

func (x *CosmosMsg) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosmosMsg.ProtoReflect.Descriptor instead.
func (*CosmosMsg) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{2}
}

func (x *CosmosMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CosmosMsg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SignAmino struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fee  *CosmosFee   `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	Msgs []*CosmosMsg `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs,omitempty"`
}

func (x *SignAmino) Reset() {
	*x = SignAmino{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignAmino) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignAmino) ProtoMessage() {}

func (x *SignAmino) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignAmino.ProtoReflect.Descriptor instead.
func (*SignAmino) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{3}
}

func (x *SignAmino) GetFee() *CosmosFee {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *SignAmino) GetMsgs() []*CosmosMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type SignDirect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BodyBytes     string `protobuf:"bytes,1,opt,name=body_bytes,json=bodyBytes,proto3" json:"body_bytes,omitempty"`
	AuthInfoBytes string `protobuf:"bytes,2,opt,name=auth_info_bytes,json=authInfoBytes,proto3" json:"auth_info_bytes,omitempty"`
	ChainId       string `protobuf:"bytes,3,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	AccountNumber string `protobuf:"bytes,4,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
}

func (x *SignDirect) Reset() {
	*x = SignDirect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignDirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignDirect) ProtoMessage() {}

func (x *SignDirect) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignDirect.ProtoReflect.Descriptor instead.
func (*SignDirect) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{4}
}

func (x *SignDirect) GetBodyBytes() string {
	if x != nil {
		return x.BodyBytes
	}
	return ""
}

func (x *SignDirect) GetAuthInfoBytes() string {
	if x != nil {
		return x.AuthInfoBytes
	}
	return ""
}

func (x *SignDirect) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *SignDirect) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type SignSolana struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawTransactions []string `protobuf:"bytes,1,rep,name=raw_transactions,json=rawTransactions,proto3" json:"raw_transactions,omitempty"` // base64 encoded transactions
}

func (x *SignSolana) Reset() {
	*x = SignSolana{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignSolana) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSolana) ProtoMessage() {}

func (x *SignSolana) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSolana.ProtoReflect.Descriptor instead.
func (*SignSolana) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{5}
}

func (x *SignSolana) GetRawTransactions() []string {
	if x != nil {
		return x.RawTransactions
	}
	return nil
}

type TonMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To        string  `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount    string  `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Payload   *string `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	StateInit *string `protobuf:"bytes,4,opt,name=state_init,json=stateInit,proto3,oneof" json:"state_init,omitempty"`
}

func (x *TonMessage) Reset() {
	*x = TonMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TonMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TonMessage) ProtoMessage() {}

func (x *TonMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TonMessage.ProtoReflect.Descriptor instead.
func (*TonMessage) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{6}
}

func (x *TonMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TonMessage) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TonMessage) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

func (x *TonMessage) GetStateInit() string {
	if x != nil && x.StateInit != nil {
		return *x.StateInit
	}
	return ""
}

type SignTon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TonMessages []*TonMessage `protobuf:"bytes,2,rep,name=ton_messages,json=tonMessages,proto3" json:"ton_messages,omitempty"`
}

func (x *SignTon) Reset() {
	*x = SignTon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTon) ProtoMessage() {}

func (x *SignTon) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTon.ProtoReflect.Descriptor instead.
func (*SignTon) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{7}
}

func (x *SignTon) GetTonMessages() []*TonMessage {
	if x != nil {
		return x.TonMessages
	}
	return nil
}

type WasmExecuteContractPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SenderAddress   string        `protobuf:"bytes,1,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	ContractAddress string        `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	ExecuteMsg      string        `protobuf:"bytes,3,opt,name=execute_msg,json=executeMsg,proto3" json:"execute_msg,omitempty"`
	Coins           []*CosmosCoin `protobuf:"bytes,4,rep,name=coins,proto3" json:"coins,omitempty"`
}

func (x *WasmExecuteContractPayload) Reset() {
	*x = WasmExecuteContractPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WasmExecuteContractPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmExecuteContractPayload) ProtoMessage() {}

func (x *WasmExecuteContractPayload) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmExecuteContractPayload.ProtoReflect.Descriptor instead.
func (*WasmExecuteContractPayload) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{8}
}

func (x *WasmExecuteContractPayload) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *WasmExecuteContractPayload) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *WasmExecuteContractPayload) GetExecuteMsg() string {
	if x != nil {
		return x.ExecuteMsg
	}
	return ""
}

func (x *WasmExecuteContractPayload) GetCoins() []*CosmosCoin {
	if x != nil {
		return x.Coins
	}
	return nil
}

// A single Bitcoin transaction input decomposed from a PSBT.
// Contains all data needed for sighash computation and verification.
type BitcoinInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash         string  `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                           // Previous txid (hex, big-endian)
	Index        uint32  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`                                        // Previous output index (vout)
	Amount       int64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`                                      // Satoshis (from witness UTXO)
	ScriptPubKey string  `protobuf:"bytes,4,opt,name=script_pub_key,json=scriptPubKey,proto3" json:"script_pub_key,omitempty"`     // Hex scriptPubKey of the UTXO being spent
	ScriptType   string  `protobuf:"bytes,5,opt,name=script_type,json=scriptType,proto3" json:"script_type,omitempty"`             // "p2wpkh", "p2pkh", "p2tr", "p2sh-p2wpkh"
	SighashType  *uint32 `protobuf:"varint,6,opt,name=sighash_type,json=sighashType,proto3,oneof" json:"sighash_type,omitempty"`   // BIP-143/341 sighash flag; when absent, treat as SIGHASH_ALL (1)
	IsOurs       bool    `protobuf:"varint,7,opt,name=is_ours,json=isOurs,proto3" json:"is_ours,omitempty"`                        // Whether this device signs this input
	RedeemScript *string `protobuf:"bytes,8,opt,name=redeem_script,json=redeemScript,proto3,oneof" json:"redeem_script,omitempty"` // For P2SH-P2WPKH: hex redeem script
	Sequence     *uint32 `protobuf:"varint,9,opt,name=sequence,proto3,oneof" json:"sequence,omitempty"`                            // nSequence; when absent, treat as 0xFFFFFFFF
}

func (x *BitcoinInput) Reset() {
	*x = BitcoinInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitcoinInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitcoinInput) ProtoMessage() {}

func (x *BitcoinInput) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitcoinInput.ProtoReflect.Descriptor instead.
func (*BitcoinInput) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{9}
}

func (x *BitcoinInput) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *BitcoinInput) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BitcoinInput) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BitcoinInput) GetScriptPubKey() string {
	if x != nil {
		return x.ScriptPubKey
	}
	return ""
}

func (x *BitcoinInput) GetScriptType() string {
	if x != nil {
		return x.ScriptType
	}
	return ""
}

func (x *BitcoinInput) GetSighashType() uint32 {
	if x != nil && x.SighashType != nil {
		return *x.SighashType
	}
	return 0
}

func (x *BitcoinInput) GetIsOurs() bool {
	if x != nil {
		return x.IsOurs
	}
	return false
}

func (x *BitcoinInput) GetRedeemScript() string {
	if x != nil && x.RedeemScript != nil {
		return *x.RedeemScript
	}
	return ""
}

func (x *BitcoinInput) GetSequence() uint32 {
	if x != nil && x.Sequence != nil {
		return *x.Sequence
	}
	return 0
}

// A single Bitcoin transaction output decomposed from a PSBT.
type BitcoinOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount       int64   `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`                                        // Satoshis
	Address      string  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                                       // Decoded address (empty for OP_RETURN)
	OpReturnData *string `protobuf:"bytes,3,opt,name=op_return_data,json=opReturnData,proto3,oneof" json:"op_return_data,omitempty"` // Hex data if OP_RETURN
	ScriptPubKey string  `protobuf:"bytes,4,opt,name=script_pub_key,json=scriptPubKey,proto3" json:"script_pub_key,omitempty"`       // Hex output scriptPubKey
	IsChange     bool    `protobuf:"varint,5,opt,name=is_change,json=isChange,proto3" json:"is_change,omitempty"`                    // Whether output is change back to sender
}

func (x *BitcoinOutput) Reset() {
	*x = BitcoinOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitcoinOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitcoinOutput) ProtoMessage() {}

func (x *BitcoinOutput) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitcoinOutput.ProtoReflect.Descriptor instead.
func (*BitcoinOutput) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{10}
}

func (x *BitcoinOutput) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BitcoinOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BitcoinOutput) GetOpReturnData() string {
	if x != nil && x.OpReturnData != nil {
		return *x.OpReturnData
	}
	return ""
}

func (x *BitcoinOutput) GetScriptPubKey() string {
	if x != nil {
		return x.ScriptPubKey
	}
	return ""
}

func (x *BitcoinOutput) GetIsChange() bool {
	if x != nil {
		return x.IsChange
	}
	return false
}

// Structured PSBT representation for Bitcoin dApp signing.
// Decomposes a BIP-174 PSBT into verifiable fields so co-signing
// devices can display transaction details and compute exact sighashes
// without receiving an opaque blob.
type SignBitcoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  uint32           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`   // Transaction version (typically 1 or 2)
	Locktime uint32           `protobuf:"varint,2,opt,name=locktime,proto3" json:"locktime,omitempty"` // Transaction locktime
	Inputs   []*BitcoinInput  `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`      // All inputs in exact PSBT order
	Outputs  []*BitcoinOutput `protobuf:"bytes,4,rep,name=outputs,proto3" json:"outputs,omitempty"`    // All outputs in exact PSBT order
}

func (x *SignBitcoin) Reset() {
	*x = SignBitcoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignBitcoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignBitcoin) ProtoMessage() {}

func (x *SignBitcoin) ProtoReflect() protoreflect.Message {
	mi := &file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignBitcoin.ProtoReflect.Descriptor instead.
func (*SignBitcoin) Descriptor() ([]byte, []int) {
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP(), []int{11}
}

func (x *SignBitcoin) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SignBitcoin) GetLocktime() uint32 {
	if x != nil {
		return x.Locktime
	}
	return 0
}

func (x *SignBitcoin) GetInputs() []*BitcoinInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *SignBitcoin) GetOutputs() []*BitcoinOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

var File_vultisig_keysign_v1_wasm_execute_contract_payload_proto protoreflect.FileDescriptor

var file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDesc = []byte{
	0x0a, 0x37, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69,
	0x67, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x73, 0x6d, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69,
	0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x3a,
	0x0a, 0x0a, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e,
	0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xd6, 0x01, 0x0a, 0x09, 0x43,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x46, 0x65, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69,
	0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x67, 0x61, 0x73, 0x12, 0x19, 0x0a, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1d,
	0x0a, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a,
	0x09, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x08, 0x66, 0x65, 0x65, 0x50, 0x61, 0x79, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x70, 0x61, 0x79, 0x65, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x67, 0x72,
	0x61, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x09, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x4d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x71, 0x0a, 0x09, 0x53, 0x69,
	0x67, 0x6e, 0x41, 0x6d, 0x69, 0x6e, 0x6f, 0x12, 0x30, 0x0a, 0x03, 0x66, 0x65, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e,
	0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x46, 0x65, 0x65, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x32, 0x0a, 0x04, 0x6d, 0x73, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73,
	0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f,
	0x73, 0x6d, 0x6f, 0x73, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x6d, 0x73, 0x67, 0x73, 0x22, 0x95, 0x01,
	0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x62, 0x6f, 0x64, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x61,
	0x75, 0x74, 0x68, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x6f, 0x6c,
	0x61, 0x6e, 0x61, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x61, 0x77, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x72,
	0x61, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x92,
	0x01, 0x0a, 0x0a, 0x54, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x69, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x69,
	0x6e, 0x69, 0x74, 0x22, 0x4d, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6e, 0x12, 0x42,
	0x0a, 0x0c, 0x74, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e,
	0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x74, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0xc6, 0x01, 0x0a, 0x1a, 0x57, 0x61, 0x73, 0x6d, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x5f, 0x6d,
	0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x4d, 0x73, 0x67, 0x12, 0x35, 0x0a, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b,
	0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e, 0x73, 0x22, 0xd3, 0x02, 0x0a, 0x0c,
	0x42, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24,
	0x0a, 0x0e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x73, 0x69, 0x67, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x0b, 0x73,
	0x69, 0x67, 0x68, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x07, 0x69, 0x73, 0x5f, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x73, 0x4f, 0x75, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d,
	0x5f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0c, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x1f, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0d, 0x48, 0x02, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x88, 0x01,
	0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x73, 0x69, 0x67, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x5f, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x22, 0xc2, 0x01, 0x0a, 0x0d, 0x42, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a, 0x0e, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x0c, 0x6f, 0x70, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01,
	0x12, 0x24, 0x0a, 0x0e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x5f, 0x70, 0x75, 0x62, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x50, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x42,
	0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x6b, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x06,
	0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76,
	0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52,
	0x06, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x76, 0x75, 0x6c, 0x74, 0x69,
	0x73, 0x69, 0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x42,
	0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x73, 0x42, 0x54, 0x0a, 0x13, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69,
	0x67, 0x2e, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e, 0x2e, 0x76, 0x31, 0x5a, 0x38, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69,
	0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x67, 0x6f, 0x2f,
	0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x69, 0x67, 0x6e,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xba, 0x02, 0x02, 0x56, 0x53, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescOnce sync.Once
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescData = file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDesc
)

func file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescGZIP() []byte {
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescOnce.Do(func() {
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescData)
	})
	return file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDescData
}

var file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_goTypes = []any{
	(*CosmosCoin)(nil),                 // 0: vultisig.keysign.v1.CosmosCoin
	(*CosmosFee)(nil),                  // 1: vultisig.keysign.v1.CosmosFee
	(*CosmosMsg)(nil),                  // 2: vultisig.keysign.v1.CosmosMsg
	(*SignAmino)(nil),                  // 3: vultisig.keysign.v1.SignAmino
	(*SignDirect)(nil),                 // 4: vultisig.keysign.v1.SignDirect
	(*SignSolana)(nil),                 // 5: vultisig.keysign.v1.SignSolana
	(*TonMessage)(nil),                 // 6: vultisig.keysign.v1.TonMessage
	(*SignTon)(nil),                    // 7: vultisig.keysign.v1.SignTon
	(*WasmExecuteContractPayload)(nil), // 8: vultisig.keysign.v1.WasmExecuteContractPayload
	(*BitcoinInput)(nil),               // 9: vultisig.keysign.v1.BitcoinInput
	(*BitcoinOutput)(nil),              // 10: vultisig.keysign.v1.BitcoinOutput
	(*SignBitcoin)(nil),                // 11: vultisig.keysign.v1.SignBitcoin
}
var file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_depIdxs = []int32{
	0,  // 0: vultisig.keysign.v1.CosmosFee.amount:type_name -> vultisig.keysign.v1.CosmosCoin
	1,  // 1: vultisig.keysign.v1.SignAmino.fee:type_name -> vultisig.keysign.v1.CosmosFee
	2,  // 2: vultisig.keysign.v1.SignAmino.msgs:type_name -> vultisig.keysign.v1.CosmosMsg
	6,  // 3: vultisig.keysign.v1.SignTon.ton_messages:type_name -> vultisig.keysign.v1.TonMessage
	0,  // 4: vultisig.keysign.v1.WasmExecuteContractPayload.coins:type_name -> vultisig.keysign.v1.CosmosCoin
	9,  // 5: vultisig.keysign.v1.SignBitcoin.inputs:type_name -> vultisig.keysign.v1.BitcoinInput
	10, // 6: vultisig.keysign.v1.SignBitcoin.outputs:type_name -> vultisig.keysign.v1.BitcoinOutput
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_init() }
func file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_init() {
	if File_vultisig_keysign_v1_wasm_execute_contract_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CosmosCoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CosmosFee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CosmosMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SignAmino); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*SignDirect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SignSolana); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TonMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SignTon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*WasmExecuteContractPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BitcoinInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BitcoinOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*SignBitcoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[1].OneofWrappers = []any{}
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[6].OneofWrappers = []any{}
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[9].OneofWrappers = []any{}
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_goTypes,
		DependencyIndexes: file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_depIdxs,
		MessageInfos:      file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_msgTypes,
	}.Build()
	File_vultisig_keysign_v1_wasm_execute_contract_payload_proto = out.File
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_rawDesc = nil
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_goTypes = nil
	file_vultisig_keysign_v1_wasm_execute_contract_payload_proto_depIdxs = nil
}
