// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/coin.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializecoin")
public inline fun coin(block: vultisig.keysign.v1.CoinKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.CoinOuterClass.Coin =
  vultisig.keysign.v1.CoinKt.Dsl._create(vultisig.keysign.v1.CoinOuterClass.Coin.newBuilder()).apply { block() }._build()
/**
 * ```
 * Coin only contains information that the app can use it to identify the relevant coin in the vault
 * ```
 *
 * Protobuf type `vultisig.keysign.v1.Coin`
 */
public object CoinKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.CoinOuterClass.Coin.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.CoinOuterClass.Coin.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.CoinOuterClass.Coin = _builder.build()

    /**
     * `string chain = 1 [json_name = "chain"];`
     */
    public var chain: kotlin.String
      @JvmName("getChain")
      get() = _builder.getChain()
      @JvmName("setChain")
      set(value) {
        _builder.setChain(value)
      }
    /**
     * `string chain = 1 [json_name = "chain"];`
     */
    public fun clearChain() {
      _builder.clearChain()
    }

    /**
     * `string ticker = 2 [json_name = "ticker"];`
     */
    public var ticker: kotlin.String
      @JvmName("getTicker")
      get() = _builder.getTicker()
      @JvmName("setTicker")
      set(value) {
        _builder.setTicker(value)
      }
    /**
     * `string ticker = 2 [json_name = "ticker"];`
     */
    public fun clearTicker() {
      _builder.clearTicker()
    }

    /**
     * `string address = 3 [json_name = "address"];`
     */
    public var address: kotlin.String
      @JvmName("getAddress")
      get() = _builder.getAddress()
      @JvmName("setAddress")
      set(value) {
        _builder.setAddress(value)
      }
    /**
     * `string address = 3 [json_name = "address"];`
     */
    public fun clearAddress() {
      _builder.clearAddress()
    }

    /**
     * `string contract_address = 4 [json_name = "contractAddress"];`
     */
    public var contractAddress: kotlin.String
      @JvmName("getContractAddress")
      get() = _builder.getContractAddress()
      @JvmName("setContractAddress")
      set(value) {
        _builder.setContractAddress(value)
      }
    /**
     * `string contract_address = 4 [json_name = "contractAddress"];`
     */
    public fun clearContractAddress() {
      _builder.clearContractAddress()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.CoinOuterClass.Coin.copy(block: `vultisig.keysign.v1`.CoinKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.CoinOuterClass.Coin =
  `vultisig.keysign.v1`.CoinKt.Dsl._create(this.toBuilder()).apply { block() }._build()

