// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/blockchain_specific.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializecoinKeyValuePair")
public inline fun coinKeyValuePair(block: vultisig.keysign.v1.CoinKeyValuePairKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair =
  vultisig.keysign.v1.CoinKeyValuePairKt.Dsl._create(vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.CoinKeyValuePair`
 */
public object CoinKeyValuePairKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair = _builder.build()

    /**
     * `string key = 1 [json_name = "key"];`
     */
    public var key: kotlin.String
      @JvmName("getKey")
      get() = _builder.getKey()
      @JvmName("setKey")
      set(value) {
        _builder.setKey(value)
      }
    /**
     * `string key = 1 [json_name = "key"];`
     */
    public fun clearKey() {
      _builder.clearKey()
    }

    /**
     * `string value = 2 [json_name = "value"];`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * `string value = 2 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair.copy(block: `vultisig.keysign.v1`.CoinKeyValuePairKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.CoinKeyValuePair =
  `vultisig.keysign.v1`.CoinKeyValuePairKt.Dsl._create(this.toBuilder()).apply { block() }._build()

