// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/erc20_approve_payload.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializeerc20ApprovePayload")
public inline fun erc20ApprovePayload(block: vultisig.keysign.v1.Erc20ApprovePayloadKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload =
  vultisig.keysign.v1.Erc20ApprovePayloadKt.Dsl._create(vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.Erc20ApprovePayload`
 */
public object Erc20ApprovePayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload = _builder.build()

    /**
     * `string amount = 1 [json_name = "amount"];`
     */
    public var amount: kotlin.String
      @JvmName("getAmount")
      get() = _builder.getAmount()
      @JvmName("setAmount")
      set(value) {
        _builder.setAmount(value)
      }
    /**
     * `string amount = 1 [json_name = "amount"];`
     */
    public fun clearAmount() {
      _builder.clearAmount()
    }

    /**
     * `string spender = 2 [json_name = "spender"];`
     */
    public var spender: kotlin.String
      @JvmName("getSpender")
      get() = _builder.getSpender()
      @JvmName("setSpender")
      set(value) {
        _builder.setSpender(value)
      }
    /**
     * `string spender = 2 [json_name = "spender"];`
     */
    public fun clearSpender() {
      _builder.clearSpender()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload.copy(block: `vultisig.keysign.v1`.Erc20ApprovePayloadKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.Erc20ApprovePayloadOuterClass.Erc20ApprovePayload =
  `vultisig.keysign.v1`.Erc20ApprovePayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

