// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/keysign_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializekeysignMessage")
public inline fun keysignMessage(block: vultisig.keysign.v1.KeysignMessageKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage =
  vultisig.keysign.v1.KeysignMessageKt.Dsl._create(vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.KeysignMessage`
 */
public object KeysignMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.getSessionId()
      @JvmName("setSessionId")
      set(value) {
        _builder.setSessionId(value)
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string service_name = 2 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 2 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string encryption_key_hex = 4 [json_name = "encryptionKeyHex"];`
     */
    public var encryptionKeyHex: kotlin.String
      @JvmName("getEncryptionKeyHex")
      get() = _builder.getEncryptionKeyHex()
      @JvmName("setEncryptionKeyHex")
      set(value) {
        _builder.setEncryptionKeyHex(value)
      }
    /**
     * `string encryption_key_hex = 4 [json_name = "encryptionKeyHex"];`
     */
    public fun clearEncryptionKeyHex() {
      _builder.clearEncryptionKeyHex()
    }

    /**
     * `.vultisig.keysign.v1.KeysignPayload keysign_payload = 5 [json_name = "keysignPayload"];`
     */
    public var keysignPayload: vultisig.keysign.v1.KeysignMessageOuterClass.KeysignPayload
      @JvmName("getKeysignPayload")
      get() = _builder.getKeysignPayload()
      @JvmName("setKeysignPayload")
      set(value) {
        _builder.setKeysignPayload(value)
      }
    /**
     * `.vultisig.keysign.v1.KeysignPayload keysign_payload = 5 [json_name = "keysignPayload"];`
     */
    public fun clearKeysignPayload() {
      _builder.clearKeysignPayload()
    }
    /**
     * `.vultisig.keysign.v1.KeysignPayload keysign_payload = 5 [json_name = "keysignPayload"];`
     * @return Whether the keysignPayload field is set.
     */
    public fun hasKeysignPayload(): kotlin.Boolean {
      return _builder.hasKeysignPayload()
    }
    public val KeysignMessageKt.Dsl.keysignPayloadOrNull: vultisig.keysign.v1.KeysignMessageOuterClass.KeysignPayload?
      get() = _builder.keysignPayloadOrNull

    /**
     * `bool use_vultisig_relay = 6 [json_name = "useVultisigRelay"];`
     */
    public var useVultisigRelay: kotlin.Boolean
      @JvmName("getUseVultisigRelay")
      get() = _builder.getUseVultisigRelay()
      @JvmName("setUseVultisigRelay")
      set(value) {
        _builder.setUseVultisigRelay(value)
      }
    /**
     * `bool use_vultisig_relay = 6 [json_name = "useVultisigRelay"];`
     */
    public fun clearUseVultisigRelay() {
      _builder.clearUseVultisigRelay()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage.copy(block: `vultisig.keysign.v1`.KeysignMessageKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessage =
  `vultisig.keysign.v1`.KeysignMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val vultisig.keysign.v1.KeysignMessageOuterClass.KeysignMessageOrBuilder.keysignPayloadOrNull: vultisig.keysign.v1.KeysignMessageOuterClass.KeysignPayload?
  get() = if (hasKeysignPayload()) getKeysignPayload() else null

