// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/blockchain_specific.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializemAYAChainSpecific")
public inline fun mAYAChainSpecific(block: vultisig.keysign.v1.MAYAChainSpecificKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific =
  vultisig.keysign.v1.MAYAChainSpecificKt.Dsl._create(vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.MAYAChainSpecific`
 */
public object MAYAChainSpecificKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific = _builder.build()

    /**
     * `uint64 account_number = 1 [json_name = "accountNumber"];`
     */
    public var accountNumber: kotlin.Long
      @JvmName("getAccountNumber")
      get() = _builder.getAccountNumber()
      @JvmName("setAccountNumber")
      set(value) {
        _builder.setAccountNumber(value)
      }
    /**
     * `uint64 account_number = 1 [json_name = "accountNumber"];`
     */
    public fun clearAccountNumber() {
      _builder.clearAccountNumber()
    }

    /**
     * `uint64 sequence = 2 [json_name = "sequence"];`
     */
    public var sequence: kotlin.Long
      @JvmName("getSequence")
      get() = _builder.getSequence()
      @JvmName("setSequence")
      set(value) {
        _builder.setSequence(value)
      }
    /**
     * `uint64 sequence = 2 [json_name = "sequence"];`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific.copy(block: `vultisig.keysign.v1`.MAYAChainSpecificKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.MAYAChainSpecific =
  `vultisig.keysign.v1`.MAYAChainSpecificKt.Dsl._create(this.toBuilder()).apply { block() }._build()

