// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/blockchain_specific.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializepolkadotSpecific")
public inline fun polkadotSpecific(block: vultisig.keysign.v1.PolkadotSpecificKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific =
  vultisig.keysign.v1.PolkadotSpecificKt.Dsl._create(vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.PolkadotSpecific`
 */
public object PolkadotSpecificKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific = _builder.build()

    /**
     * `string recent_block_hash = 1 [json_name = "recentBlockHash"];`
     */
    public var recentBlockHash: kotlin.String
      @JvmName("getRecentBlockHash")
      get() = _builder.getRecentBlockHash()
      @JvmName("setRecentBlockHash")
      set(value) {
        _builder.setRecentBlockHash(value)
      }
    /**
     * `string recent_block_hash = 1 [json_name = "recentBlockHash"];`
     */
    public fun clearRecentBlockHash() {
      _builder.clearRecentBlockHash()
    }

    /**
     * `uint64 nonce = 2 [json_name = "nonce"];`
     */
    public var nonce: kotlin.Long
      @JvmName("getNonce")
      get() = _builder.getNonce()
      @JvmName("setNonce")
      set(value) {
        _builder.setNonce(value)
      }
    /**
     * `uint64 nonce = 2 [json_name = "nonce"];`
     */
    public fun clearNonce() {
      _builder.clearNonce()
    }

    /**
     * `string current_block_number = 3 [json_name = "currentBlockNumber"];`
     */
    public var currentBlockNumber: kotlin.String
      @JvmName("getCurrentBlockNumber")
      get() = _builder.getCurrentBlockNumber()
      @JvmName("setCurrentBlockNumber")
      set(value) {
        _builder.setCurrentBlockNumber(value)
      }
    /**
     * `string current_block_number = 3 [json_name = "currentBlockNumber"];`
     */
    public fun clearCurrentBlockNumber() {
      _builder.clearCurrentBlockNumber()
    }

    /**
     * `uint32 spec_version = 4 [json_name = "specVersion"];`
     */
    public var specVersion: kotlin.Int
      @JvmName("getSpecVersion")
      get() = _builder.getSpecVersion()
      @JvmName("setSpecVersion")
      set(value) {
        _builder.setSpecVersion(value)
      }
    /**
     * `uint32 spec_version = 4 [json_name = "specVersion"];`
     */
    public fun clearSpecVersion() {
      _builder.clearSpecVersion()
    }

    /**
     * `uint32 transaction_version = 5 [json_name = "transactionVersion"];`
     */
    public var transactionVersion: kotlin.Int
      @JvmName("getTransactionVersion")
      get() = _builder.getTransactionVersion()
      @JvmName("setTransactionVersion")
      set(value) {
        _builder.setTransactionVersion(value)
      }
    /**
     * `uint32 transaction_version = 5 [json_name = "transactionVersion"];`
     */
    public fun clearTransactionVersion() {
      _builder.clearTransactionVersion()
    }

    /**
     * `string genesis_hash = 6 [json_name = "genesisHash"];`
     */
    public var genesisHash: kotlin.String
      @JvmName("getGenesisHash")
      get() = _builder.getGenesisHash()
      @JvmName("setGenesisHash")
      set(value) {
        _builder.setGenesisHash(value)
      }
    /**
     * `string genesis_hash = 6 [json_name = "genesisHash"];`
     */
    public fun clearGenesisHash() {
      _builder.clearGenesisHash()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific.copy(block: `vultisig.keysign.v1`.PolkadotSpecificKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.BlockchainSpecific.PolkadotSpecific =
  `vultisig.keysign.v1`.PolkadotSpecificKt.Dsl._create(this.toBuilder()).apply { block() }._build()

