// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keysign/v1/utxo_info.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keysign.v1;

@kotlin.jvm.JvmName("-initializeutxoInfo")
public inline fun utxoInfo(block: vultisig.keysign.v1.UtxoInfoKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo =
  vultisig.keysign.v1.UtxoInfoKt.Dsl._create(vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keysign.v1.UtxoInfo`
 */
public object UtxoInfoKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo = _builder.build()

    /**
     * `string hash = 1 [json_name = "hash"];`
     */
    public var hash: kotlin.String
      @JvmName("getHash")
      get() = _builder.getHash()
      @JvmName("setHash")
      set(value) {
        _builder.setHash(value)
      }
    /**
     * `string hash = 1 [json_name = "hash"];`
     */
    public fun clearHash() {
      _builder.clearHash()
    }

    /**
     * `int64 amount = 2 [json_name = "amount"];`
     */
    public var amount: kotlin.Long
      @JvmName("getAmount")
      get() = _builder.getAmount()
      @JvmName("setAmount")
      set(value) {
        _builder.setAmount(value)
      }
    /**
     * `int64 amount = 2 [json_name = "amount"];`
     */
    public fun clearAmount() {
      _builder.clearAmount()
    }

    /**
     * `uint32 index = 3 [json_name = "index"];`
     */
    public var index: kotlin.Int
      @JvmName("getIndex")
      get() = _builder.getIndex()
      @JvmName("setIndex")
      set(value) {
        _builder.setIndex(value)
      }
    /**
     * `uint32 index = 3 [json_name = "index"];`
     */
    public fun clearIndex() {
      _builder.clearIndex()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo.copy(block: `vultisig.keysign.v1`.UtxoInfoKt.Dsl.() -> kotlin.Unit): vultisig.keysign.v1.UtxoInfoOuterClass.UtxoInfo =
  `vultisig.keysign.v1`.UtxoInfoKt.Dsl._create(this.toBuilder()).apply { block() }._build()

