// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keygen/v1/keygen_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keygen.v1;

@kotlin.jvm.JvmName("-initializekeygenMessage")
public inline fun keygenMessage(block: vultisig.keygen.v1.KeygenMessageKt.Dsl.() -> kotlin.Unit): vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage =
  vultisig.keygen.v1.KeygenMessageKt.Dsl._create(vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keygen.v1.KeygenMessage`
 */
public object KeygenMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.getSessionId()
      @JvmName("setSessionId")
      set(value) {
        _builder.setSessionId(value)
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string hex_chain_code = 2 [json_name = "hexChainCode"];`
     */
    public var hexChainCode: kotlin.String
      @JvmName("getHexChainCode")
      get() = _builder.getHexChainCode()
      @JvmName("setHexChainCode")
      set(value) {
        _builder.setHexChainCode(value)
      }
    /**
     * `string hex_chain_code = 2 [json_name = "hexChainCode"];`
     */
    public fun clearHexChainCode() {
      _builder.clearHexChainCode()
    }

    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string encryption_key_hex = 4 [json_name = "encryptionKeyHex"];`
     */
    public var encryptionKeyHex: kotlin.String
      @JvmName("getEncryptionKeyHex")
      get() = _builder.getEncryptionKeyHex()
      @JvmName("setEncryptionKeyHex")
      set(value) {
        _builder.setEncryptionKeyHex(value)
      }
    /**
     * `string encryption_key_hex = 4 [json_name = "encryptionKeyHex"];`
     */
    public fun clearEncryptionKeyHex() {
      _builder.clearEncryptionKeyHex()
    }

    /**
     * `bool use_vultisig_relay = 5 [json_name = "useVultisigRelay"];`
     */
    public var useVultisigRelay: kotlin.Boolean
      @JvmName("getUseVultisigRelay")
      get() = _builder.getUseVultisigRelay()
      @JvmName("setUseVultisigRelay")
      set(value) {
        _builder.setUseVultisigRelay(value)
      }
    /**
     * `bool use_vultisig_relay = 5 [json_name = "useVultisigRelay"];`
     */
    public fun clearUseVultisigRelay() {
      _builder.clearUseVultisigRelay()
    }

    /**
     * `string vault_name = 6 [json_name = "vaultName"];`
     */
    public var vaultName: kotlin.String
      @JvmName("getVaultName")
      get() = _builder.getVaultName()
      @JvmName("setVaultName")
      set(value) {
        _builder.setVaultName(value)
      }
    /**
     * `string vault_name = 6 [json_name = "vaultName"];`
     */
    public fun clearVaultName() {
      _builder.clearVaultName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage.copy(block: `vultisig.keygen.v1`.KeygenMessageKt.Dsl.() -> kotlin.Unit): vultisig.keygen.v1.KeygenMessageOuterClass.KeygenMessage =
  `vultisig.keygen.v1`.KeygenMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

