// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/keygen/v1/reshare_message.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.keygen.v1;

@kotlin.jvm.JvmName("-initializereshareMessage")
public inline fun reshareMessage(block: vultisig.keygen.v1.ReshareMessageKt.Dsl.() -> kotlin.Unit): vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage =
  vultisig.keygen.v1.ReshareMessageKt.Dsl._create(vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `vultisig.keygen.v1.ReshareMessage`
 */
public object ReshareMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage = _builder.build()

    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public var sessionId: kotlin.String
      @JvmName("getSessionId")
      get() = _builder.getSessionId()
      @JvmName("setSessionId")
      set(value) {
        _builder.setSessionId(value)
      }
    /**
     * `string session_id = 1 [json_name = "sessionId"];`
     */
    public fun clearSessionId() {
      _builder.clearSessionId()
    }

    /**
     * `string hex_chain_code = 2 [json_name = "hexChainCode"];`
     */
    public var hexChainCode: kotlin.String
      @JvmName("getHexChainCode")
      get() = _builder.getHexChainCode()
      @JvmName("setHexChainCode")
      set(value) {
        _builder.setHexChainCode(value)
      }
    /**
     * `string hex_chain_code = 2 [json_name = "hexChainCode"];`
     */
    public fun clearHexChainCode() {
      _builder.clearHexChainCode()
    }

    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public var serviceName: kotlin.String
      @JvmName("getServiceName")
      get() = _builder.getServiceName()
      @JvmName("setServiceName")
      set(value) {
        _builder.setServiceName(value)
      }
    /**
     * `string service_name = 3 [json_name = "serviceName"];`
     */
    public fun clearServiceName() {
      _builder.clearServiceName()
    }

    /**
     * `string public_key_ecdsa = 4 [json_name = "publicKeyEcdsa"];`
     */
    public var publicKeyEcdsa: kotlin.String
      @JvmName("getPublicKeyEcdsa")
      get() = _builder.getPublicKeyEcdsa()
      @JvmName("setPublicKeyEcdsa")
      set(value) {
        _builder.setPublicKeyEcdsa(value)
      }
    /**
     * `string public_key_ecdsa = 4 [json_name = "publicKeyEcdsa"];`
     */
    public fun clearPublicKeyEcdsa() {
      _builder.clearPublicKeyEcdsa()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OldPartiesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @return A list containing the oldParties.
     */
    public val oldParties: com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getOldPartiesList()
      )
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @param value The oldParties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addOldParties")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.add(value: kotlin.String) {
      _builder.addOldParties(value)
    }
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @param value The oldParties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignOldParties")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @param values The oldParties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllOldParties")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllOldParties(values)
    }
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @param values The oldParties to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllOldParties")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     * @param index The index to set the value at.
     * @param value The oldParties to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setOldParties")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setOldParties(index, value)
    }/**
     * `repeated string old_parties = 5 [json_name = "oldParties"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearOldParties")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, OldPartiesProxy>.clear() {
      _builder.clearOldParties()
    }
    /**
     * `string encryption_key_hex = 6 [json_name = "encryptionKeyHex"];`
     */
    public var encryptionKeyHex: kotlin.String
      @JvmName("getEncryptionKeyHex")
      get() = _builder.getEncryptionKeyHex()
      @JvmName("setEncryptionKeyHex")
      set(value) {
        _builder.setEncryptionKeyHex(value)
      }
    /**
     * `string encryption_key_hex = 6 [json_name = "encryptionKeyHex"];`
     */
    public fun clearEncryptionKeyHex() {
      _builder.clearEncryptionKeyHex()
    }

    /**
     * `bool use_vultisig_relay = 7 [json_name = "useVultisigRelay"];`
     */
    public var useVultisigRelay: kotlin.Boolean
      @JvmName("getUseVultisigRelay")
      get() = _builder.getUseVultisigRelay()
      @JvmName("setUseVultisigRelay")
      set(value) {
        _builder.setUseVultisigRelay(value)
      }
    /**
     * `bool use_vultisig_relay = 7 [json_name = "useVultisigRelay"];`
     */
    public fun clearUseVultisigRelay() {
      _builder.clearUseVultisigRelay()
    }

    /**
     * `string old_reshare_prefix = 8 [json_name = "oldResharePrefix"];`
     */
    public var oldResharePrefix: kotlin.String
      @JvmName("getOldResharePrefix")
      get() = _builder.getOldResharePrefix()
      @JvmName("setOldResharePrefix")
      set(value) {
        _builder.setOldResharePrefix(value)
      }
    /**
     * `string old_reshare_prefix = 8 [json_name = "oldResharePrefix"];`
     */
    public fun clearOldResharePrefix() {
      _builder.clearOldResharePrefix()
    }

    /**
     * `string vault_name = 9 [json_name = "vaultName"];`
     */
    public var vaultName: kotlin.String
      @JvmName("getVaultName")
      get() = _builder.getVaultName()
      @JvmName("setVaultName")
      set(value) {
        _builder.setVaultName(value)
      }
    /**
     * `string vault_name = 9 [json_name = "vaultName"];`
     */
    public fun clearVaultName() {
      _builder.clearVaultName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage.copy(block: `vultisig.keygen.v1`.ReshareMessageKt.Dsl.() -> kotlin.Unit): vultisig.keygen.v1.ReshareMessageOuterClass.ReshareMessage =
  `vultisig.keygen.v1`.ReshareMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

