// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vultisig/keysign/v1/signature.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VSSignature {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var msg: String = String()

  public var r: String = String()

  public var s: String = String()

  public var derSignature: String = String()

  public var recoveryID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension VSSignature: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vultisig.keysign.v1"

extension VSSignature: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Signature"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "msg"),
    2: .same(proto: "r"),
    3: .same(proto: "s"),
    4: .standard(proto: "der_signature"),
    5: .standard(proto: "recovery_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.msg) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.r) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.s) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.derSignature) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.recoveryID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.msg.isEmpty {
      try visitor.visitSingularStringField(value: self.msg, fieldNumber: 1)
    }
    if !self.r.isEmpty {
      try visitor.visitSingularStringField(value: self.r, fieldNumber: 2)
    }
    if !self.s.isEmpty {
      try visitor.visitSingularStringField(value: self.s, fieldNumber: 3)
    }
    if !self.derSignature.isEmpty {
      try visitor.visitSingularStringField(value: self.derSignature, fieldNumber: 4)
    }
    if !self.recoveryID.isEmpty {
      try visitor.visitSingularStringField(value: self.recoveryID, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSignature, rhs: VSSignature) -> Bool {
    if lhs.msg != rhs.msg {return false}
    if lhs.r != rhs.r {return false}
    if lhs.s != rhs.s {return false}
    if lhs.derSignature != rhs.derSignature {return false}
    if lhs.recoveryID != rhs.recoveryID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
