// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vultisig/keysign/v1/swapkit_swap_payload.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// SwapKit-routed swap whose wire shape doesn't fit the EVM-typed
/// OneInchSwapPayload. Used for BTC PSBT, Sui PTB, TRON nested-object,
/// TON transfer array, and Cardano deposit-only flows returned by
/// POST /v3/swap on https://api.swapkit.dev.
///
/// EVM and Solana SwapKit swaps continue to ride OneInchSwapPayload —
/// their /v3/swap shape matches OneInchQuote 1:1 and stays typed at the
/// proto layer. The `provider` string field on OneInchSwapPayload
/// disambiguates the aggregator at the peer.
///
/// The flexibility here lives in tx_payload (a bytes passthrough opaque
/// to commondata) and tx_type (a string discriminator the cosigning
/// peer uses to dispatch to the right per-chain signer). Cosigning
/// peers MUST tolerate unknown tx_type values — drop through to an
/// "unsupported provider" UI rather than crashing the decode.
public struct VSSwapKitSwapPayload {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Identity — same as every other swap payload.
  public var fromCoin: VSCoin {
    get {return _storage._fromCoin ?? VSCoin()}
    set {_uniqueStorage()._fromCoin = newValue}
  }
  /// Returns true if `fromCoin` has been explicitly set.
  public var hasFromCoin: Bool {return _storage._fromCoin != nil}
  /// Clears the value of `fromCoin`. Subsequent reads from it will return its default value.
  public mutating func clearFromCoin() {_uniqueStorage()._fromCoin = nil}

  public var toCoin: VSCoin {
    get {return _storage._toCoin ?? VSCoin()}
    set {_uniqueStorage()._toCoin = newValue}
  }
  /// Returns true if `toCoin` has been explicitly set.
  public var hasToCoin: Bool {return _storage._toCoin != nil}
  /// Clears the value of `toCoin`. Subsequent reads from it will return its default value.
  public mutating func clearToCoin() {_uniqueStorage()._toCoin = nil}

  /// Raw, in source-asset base units.
  public var fromAmount: String {
    get {return _storage._fromAmount}
    set {_uniqueStorage()._fromAmount = newValue}
  }

  /// Human-readable, decimal-formatted expected output amount.
  public var toAmountDecimal: String {
    get {return _storage._toAmountDecimal}
    set {_uniqueStorage()._toAmountDecimal = newValue}
  }

  /// SwapKit's `meta.txType` verbatim. Drives the peer-side dispatcher:
  ///   "PSBT"     — tx_payload is a base64-decoded BTC PSBT
  ///   "TRON"     — tx_payload is a JSON-encoded TronWeb transaction object
  ///   "TON"      — tx_payload is a JSON-encoded [{address, amount}] array
  ///   "SUI"      — tx_payload is a base64-decoded Sui PTB
  ///   "CARDANO"  — tx_payload is empty (deposit-only flow);
  ///                use target_address + from_amount to build a plain send
  ///
  /// Forward-compatible: new SwapKit chains land here without a commondata
  /// bump, so long as the client SDK on each platform learns to decode the
  /// new tx_type string. Peers that don't recognise a tx_type MUST fall
  /// through to an "unsupported provider" UI rather than crash.
  public var txType: String {
    get {return _storage._txType}
    set {_uniqueStorage()._txType = newValue}
  }

  /// Raw unsigned-transaction bytes returned by POST /v3/swap.
  ///
  /// Encoding by tx_type:
  ///   PSBT     — base64-decoded PSBT bytes
  ///   SUI      — base64-decoded Sui PTB bytes
  ///   TRON     — UTF-8 bytes of the canonical JSON of the TronWeb object
  ///   TON      — UTF-8 bytes of the canonical JSON of the transfer array
  ///   CARDANO  — empty bytes (deposit-only flow)
  ///
  /// Bytes rather than string so binary payloads (PSBT, PTB) don't need
  /// base64 round-tripping. Object-shaped payloads are JSON-encoded on
  /// the initiator and decoded on the peer; canonical key ordering keeps
  /// the digest deterministic.
  public var txPayload: Data {
    get {return _storage._txPayload}
    set {_uniqueStorage()._txPayload = newValue}
  }

  /// Deposit address on the source chain. For PSBT this duplicates info
  /// also encoded inside tx_payload; for deposit-only chains (Cardano)
  /// this is the only routing info available.
  public var targetAddress: String {
    get {return _storage._targetAddress}
    set {_uniqueStorage()._targetAddress = newValue}
  }

  /// THORChain-style inbound vault address. Optional — populated only for
  /// routes that go through TC-style inbound monitoring. Rare in SwapKit
  /// since the iOS / Android / SDK clients filter THORChain/Maya routes
  /// out client-side, but kept for forward compatibility.
  public var inboundAddress: String {
    get {return _storage._inboundAddress ?? String()}
    set {_uniqueStorage()._inboundAddress = newValue}
  }
  /// Returns true if `inboundAddress` has been explicitly set.
  public var hasInboundAddress: Bool {return _storage._inboundAddress != nil}
  /// Clears the value of `inboundAddress`. Subsequent reads from it will return its default value.
  public mutating func clearInboundAddress() {_uniqueStorage()._inboundAddress = nil}

  /// Optional memo. SwapKit V3 returned null for every chain spike result
  /// we captured; field exists for forward compatibility with providers
  /// we haven't observed.
  public var memo: String {
    get {return _storage._memo ?? String()}
    set {_uniqueStorage()._memo = newValue}
  }
  /// Returns true if `memo` has been explicitly set.
  public var hasMemo: Bool {return _storage._memo != nil}
  /// Clears the value of `memo`. Subsequent reads from it will return its default value.
  public mutating func clearMemo() {_uniqueStorage()._memo = nil}

  /// Sub-provider tag for the verify screen, e.g. "CHAINFLIP", "NEAR",
  /// "GARDEN", "FLASHNET", "HARBOR". Verbatim from route.providers[0]
  /// in the /v3/quote response.
  public var subProvider: String {
    get {return _storage._subProvider}
    set {_uniqueStorage()._subProvider = newValue}
  }

  /// SwapKit swap identifier — persisted for tracking and analytics.
  /// Doesn't participate in signing. NOT accepted by POST /track —
  /// tracking still keys off the broadcast hash + source chain id.
  public var swapID: String {
    get {return _storage._swapID}
    set {_uniqueStorage()._swapID = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

#if swift(>=5.5) && canImport(_Concurrency)
extension VSSwapKitSwapPayload: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "vultisig.keysign.v1"

extension VSSwapKitSwapPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SwapKitSwapPayload"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "from_coin"),
    2: .standard(proto: "to_coin"),
    3: .standard(proto: "from_amount"),
    4: .standard(proto: "to_amount_decimal"),
    5: .standard(proto: "tx_type"),
    6: .standard(proto: "tx_payload"),
    7: .standard(proto: "target_address"),
    8: .standard(proto: "inbound_address"),
    9: .same(proto: "memo"),
    10: .standard(proto: "sub_provider"),
    11: .standard(proto: "swap_id"),
  ]

  fileprivate class _StorageClass {
    var _fromCoin: VSCoin? = nil
    var _toCoin: VSCoin? = nil
    var _fromAmount: String = String()
    var _toAmountDecimal: String = String()
    var _txType: String = String()
    var _txPayload: Data = Data()
    var _targetAddress: String = String()
    var _inboundAddress: String? = nil
    var _memo: String? = nil
    var _subProvider: String = String()
    var _swapID: String = String()

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _fromCoin = source._fromCoin
      _toCoin = source._toCoin
      _fromAmount = source._fromAmount
      _toAmountDecimal = source._toAmountDecimal
      _txType = source._txType
      _txPayload = source._txPayload
      _targetAddress = source._targetAddress
      _inboundAddress = source._inboundAddress
      _memo = source._memo
      _subProvider = source._subProvider
      _swapID = source._swapID
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._fromCoin) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._toCoin) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._fromAmount) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._toAmountDecimal) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._txType) }()
        case 6: try { try decoder.decodeSingularBytesField(value: &_storage._txPayload) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._targetAddress) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._inboundAddress) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._memo) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._subProvider) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._swapID) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._fromCoin {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._toCoin {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._fromAmount.isEmpty {
        try visitor.visitSingularStringField(value: _storage._fromAmount, fieldNumber: 3)
      }
      if !_storage._toAmountDecimal.isEmpty {
        try visitor.visitSingularStringField(value: _storage._toAmountDecimal, fieldNumber: 4)
      }
      if !_storage._txType.isEmpty {
        try visitor.visitSingularStringField(value: _storage._txType, fieldNumber: 5)
      }
      if !_storage._txPayload.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._txPayload, fieldNumber: 6)
      }
      if !_storage._targetAddress.isEmpty {
        try visitor.visitSingularStringField(value: _storage._targetAddress, fieldNumber: 7)
      }
      try { if let v = _storage._inboundAddress {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._memo {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      if !_storage._subProvider.isEmpty {
        try visitor.visitSingularStringField(value: _storage._subProvider, fieldNumber: 10)
      }
      if !_storage._swapID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._swapID, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VSSwapKitSwapPayload, rhs: VSSwapKitSwapPayload) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._fromCoin != rhs_storage._fromCoin {return false}
        if _storage._toCoin != rhs_storage._toCoin {return false}
        if _storage._fromAmount != rhs_storage._fromAmount {return false}
        if _storage._toAmountDecimal != rhs_storage._toAmountDecimal {return false}
        if _storage._txType != rhs_storage._txType {return false}
        if _storage._txPayload != rhs_storage._txPayload {return false}
        if _storage._targetAddress != rhs_storage._targetAddress {return false}
        if _storage._inboundAddress != rhs_storage._inboundAddress {return false}
        if _storage._memo != rhs_storage._memo {return false}
        if _storage._subProvider != rhs_storage._subProvider {return false}
        if _storage._swapID != rhs_storage._swapID {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
