// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vultisig/vault/v1/vault.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package vultisig.vault.v1;

